### ISSUE TITLE
Long training time for the first stage when the signal length exceeds 0.6s

### ISSUE THREAD

**Issue by Sungden** [osmanberke/Deep-SSVEP-BCI#4]
Hi, thanks for your excellent work! When I used your code on the benchmark dataset, I met a problem. When the input signal length is 0.1-0.5s, the training time for the first stage is short( within 30 minutes), but it sharply jumps to 800+ minutes when the input signal length is 0.6s. Is it normal, and why? Has anyone else had the same question? 
Thanks!

**Comment by osmanberke** [comment]
Hi,

Thank you for using our code.  We have never experienced the problem that you mention (the first stage's training time is around 70 minutes on NVIDIA GeForce GTX 1650 for 1 second of signal length). Because of that, I am not quite sure of the reason for this problem. My guess is that the reason for the problem would be a lack of memory in your GPU. You may try to run the first stage on your CPU for signal lengths higher than 0.5 seconds. With this way, the training time should take much less time than 800+ minutes. I hope my answer helps you to solve your problem. If you have further questions, I will be happy to answer those too.

**Comment by Sungden** [comment]
Thanks. I will have a try.

Osman Berke Guney ***@***.***> 於 2022年10月17日週一 下午11:42寫道：
